# Site settings
title: Sinan Çalışır
email: 
description: "Makine öğrenmesi ve Derin Öğrenme"
baseurl: ""
url: "http://snnclsr.github.io"
twitter_username: snnclsr
github_username:  snnclsr

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
