# Site settings
title: Sinan Çalışır
email: 
description: "Makine öğrenmesi ve Derin Öğrenme"
baseurl: "/sinancalisir.com"
url: ""
twitter_username: snnclsr
github_username:  snnclsr

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
